### ISSUE TITLE
Wrong paths in routing.yml

### ISSUE THREAD

**Issue by AmandaHarrer1** [asioso/pimcore-quicktranslate-module#2]
When I tried to use the module I got an error message (See attached image). 
![ErrorMessage](https://user-images.githubusercontent.com/68283316/87428435-9f0e0b80-c5e2-11ea-8c9e-e7705abdec80.PNG)

I was able to solve it by changing the routes in the routing.yml from "AsiosoQuickTranslateBundle:.." to "QuickTranslateBundle:..."

**Comment by thornwishstalon** [comment]
Hi @AmandaHarrer1 

try updating the package to the latest release, that should include @ascheider 's fix
