### ISSUE TITLE
Ajax responsen in all controllers does not work because of template lookup

### ISSUE THREAD

**Issue by ascheider** [asioso/pimcore-quicktranslate-module#3]
All ajax responses in all controllers does not work, because of template lookups, so you will get no ajax response.

**Comment by thornwishstalon** [comment]
Hi @ascheider 
you are right.  looks like we overlooked some details during the carve-out of the bundle.

thanks for the fix ;)

**Comment by ascheider** [comment]
@thornwishstalon No problem. Thanks for the quick release 👍
